name: Get and push images

on:
  push:
    branches:
      - master
  schedule:
    - cron:  '0 12 * * *'

jobs:
  build:
    name: Get cards
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [13.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Npm run
    - run: |
        npm ci
        npm run dist:clone
        npm run card-images
        npm run dist:push
      env:
        CI: true
